### PR TITLE
	Leap Recorder now exports to JSON and works with Orion

### PR DESCRIPTION
**Pull request by bridgewaterrobbie**

### CODE REVIEW

**Comment by Victorma** [comment]
Hi @bridgewaterrobbie I've been reviewing what you've done and it looks very nice! 

However I have some better ideas to approach what you've done. As far as I know, you've re-implemented LeapHandController to redirect original frames to the LeapRecorder and bypassed the fixed frame to playback the recorded one.

My idea is, LeapMotion works like this:
image

So, we can create an midde way adapter that can do the job without having to change any of the existing components which is WAY better to response to future updates. Also, the code is less coupled, where clearly we have a specific provider for what we want to do:
image

I started to work around this idea in this class: https://github.com/Victorma/LeapTrainer.CSharp/blob/master/Assets/Utils/RecordedServiceProvider.cs
But as you can see it only works as a Playback and has no user input control. It was going to replace the "tutorial" that appears in my SignAdventure game.

Anyway, I'll merge this and I'll work on in this idea (unless you want to) soon.
I expect to have a LeapMotion device from a friend soon.

Thanks for all!

**Comment by bridgewaterrobbie** [comment]
@Victorma 
I can definitely see the advantages to that long term, and my solution was somewhat hacked in, though I actually based it off of the official Leap Frame-Recorder sample app from V2 (Which also used a replacement for the hand controller, though the LeapRecorder script was more basic and thus some of the playback code had to be done in the handcontroller method). I am actually not sure where you got the current LeapRecorder script from. 

Your solution is more robust though, and results in only one script needing editing with updates. My only suggestion would be to fold RecorderProvider into LeapClassifier so it is all one object (Once I finally understood LeapRecorder I was somewhat surprised at its relative simplicity- just capture the frames and put them in a list, serialized for some reason).

One other cool feature idea, that would get the benefit of roboleary's version of recording things but in a different way: The ability to "Trim" a recording during playback. Press a button during playback, and then it will throw away all frames after the current frame_index_ . Could make development of new gestures a bit quicker to get rid of "I pressed this button at the end". 

I probably wont be able to spend too much time improving this code for right now, though I do want to. My group was essentially making an AR dev environment from a few pieces of software, and though it was a lot harder it also became a bit of our focus (So future devs wont have to try piecing things together in the same way). We need to move onto our main project for now, but I will definitely revisit this after.

**Comment by bridgewaterrobbie** [comment]
@Victorma 
have you had any luck getting this new version to detect a gesture in testing? I have been trying to get the old version to work, but consistently getting either errors where something tries to pass NaN (Which Leaptrainer gets as 0% match for everything) or other exceptions. This new version you pushed does not seem to do anything different, but I doubt you wouldn't notice that unless you just haven't gotten your leap yet, which leads me to wonder if it is an issue with my configuration?

Thanks for any input

**Comment by Victorma** [comment]
Yeah, I'm doing tests. As far as I know, for some reason during the total calculation of the gesture distance, there are some frames that are placed wrong, causing it to reach Infinity as final value. Then, when the algorithm slices the gesture it fails and puts NaN there.

I'll analyze if there is a way to detect and remove that "out of bounds" frames to see if the algorythm works again.

**Comment by bridgewaterrobbie** [comment]
I wrote a method that seems to help some, but not solve the problem (I am honestly not sure how it is not solving the problem though)

```
List<Point> removeInfin(List<Point> points)
{

    List<Point> scrubbedPoints = new List<Point>();
    Point lastPoint = new Point(0, 0, 0, 0);
    foreach (Point p in points)
    {
        if (float.IsInfinity(p.x) || float.IsNaN(p.x))
        {
            scrubbedPoints.Add(lastPoint);
            //  Debug.Log("Got a bad one! I=" + i);
        }
        else
        {
            scrubbedPoints.Add(p);
            lastPoint = p;
            //Debug.Log("Got an ok one! I=" + i);
        }

    }
    return scrubbedPoints;
}
```

I added that to the processing step. While I can imagine some issues with it, I figured it would at least remove the errors, but they still crop up often.

**Comment by Victorma** [comment]
Hey @bridgewaterrobbie ! I've made another approach to filter the corrupted frames in order to remove the whole frame instead of just the point.
Also I've made some fixes to the correlation (tbh idk how was that working at all the way it was done...)
Anyway, it's working now, needs tweaks to the variables, but it's working.

**Comment by bridgewaterrobbie** [comment]
Dude you are awesome, we had just given up and were either switching to V2 or the Kinect. 

Can I start working on this now, or should I wait on you to tweak the variables in Git? Any changes in use?

Also if you don’t mid, how did you fix it? I created a filter that checked each inputed frame (In the process method) for infinity and NaN and I still couldnt make it work. Its been driving me up the wall for the past few weeks.

Thank you again.

**Comment by Victorma** [comment]
It's working, but test it with different recording to see if it's really detecting the gestures correctly or not, and make some tweaks to it, specially in:
- https://github.com/bridgewaterrobbie/LeapTrainer.CSharp/blob/master/Assets/LeapClasifier/LeapTrainer.cs#L872: Here (the commented line bellow was my tweak for sign adventure). You'll get as output the nearest gesture value.
- https://github.com/bridgewaterrobbie/LeapTrainer.CSharp/blob/master/Assets/LeapClasifier/LeapTrainer.cs#L67: Here to increase the hit threshold in a basic way. The higher the more strict...
- https://github.com/bridgewaterrobbie/LeapTrainer.CSharp/blob/master/Assets/LeapClasifier/GeometricalMatcher.cs#L12: Here to increase the precision of the GeometricalTemplateMatcher, but also the recognition time.

Basically those three. Also, here are my confortable values for testing. 
image

The filtering was very simple, done when the recognizer was converting the frame to its format and filtering by the distance of the origin to the point:

``` csharp
    /**
     * Frame discardation 
     */
    private bool IsGoodFrame(Frame frame)
    {
        return frame.Hands.TrueForAll(h => IsGoodVector(h.StabilizedPalmPosition) && h.Fingers.TrueForAll(f => IsGoodVector(f.StabilizedTipPosition)));
    }

    private bool IsGoodVector(Leap.Vector v)
    {
        return !float.IsInfinity(Point.Distance(new Point(), new Point(v.x, v.y, v.z, 0)));
    }

    private void recordFrame(Frame frame, Frame lastFrame)
    {
        if (!IsGoodFrame(frame))
        {
            //Debug.Log("Frame discarded...");
            return;
        }

        foreach (var hand in frame.Hands)
        {
            recordVector(hand.StabilizedPalmPosition);
            foreach (var finger in hand.Fingers)
            {
                recordVector(finger.StabilizedTipPosition);
            }
        }
    }
```

But there were some very critical bugs in the geometrical template matcher. For example, it was calculating the minimum starting with a min value of negative infinite instead of positive infinity, causing it never find a minimum. Also, the check of trying to access to the lists of points was causing it to skip almost every point, and finally, when the gesture and the saved gesture didn't had the same amount of frames, it was not able to find a minimum (because all the frames were matched previously) and it was accessing to an array with a -1 value.

I am sure I commited these errors but, honestly, dont know how the fuck it was working for me in sign adventure hehe. Maybe I fixed it there but not here in the main repo...

I am not sure when I'm having the Leap again, but I think this could be a good starting point for you 😄 

Cheers!

**Comment by bridgewaterrobbie** [comment]
One of the things I tried was replacing it with a directly modified $P, and I realize how some of those things were working (IE it assumes that all gestures are the same length due to the processing it undergoes) but that didn’t solve all the issues. Really glad you figured it out.

Did you sell your leap after? If you got one just to help us out I really owe you one then.

**Comment by Victorma** [comment]
@bridgewaterrobbie I've never owned a Leap at all hehe. The first one belonged to a teacher I met during my erasmus. Then, I had one from a friend during a couple of days. Then I got another for a few days from another guy in my school. Sadly I have to give it back to him tomorrow so I tried my best to fix this today at least. I'll need to get another one from another person to fix the Sign Adventure I guess xD

**Comment by bridgewaterrobbie** [comment]
Dude Ill send you a leap as a big thanks if you want, seriously. I kind of owe you if this works, our project was going to be so inferior to what we wanted it to be.

**Comment by bridgewaterrobbie** [comment]
@Victorma bad news.

Your code is cleaner than mine, and you went about it in a different way, but you got to the same point I did before giving up. It doesn't crash, but you end up scrubbing so many frames that everything is a positive match, and not necessarily even for the pose that is most similar to what you did. 

You can make a fist and hold it still for a pose, and get a crazy high match percentage from waving an open palm around.

It is all downright strange IMO, since the poses you recorded in V2 for your sign adventure can be properly matched when running the V3 API (Something I have even tested by making new gestures in V2 on another device, porting them over and having decent but not great luck getting them recognized).

**Comment by Victorma** [comment]
@bridgewaterrobbie I think we can fix it other way, then, to avoid remove many frames.

The problem I detected was in the "h.StabilizedPalmPosition" as its z component becomes reaaaaaally big. Maybe we can detect if that has an absurd value and replace it with the value of the previous frame value instead (of course you'll lose some data, but you'll win the finger values instead).

Other way, could be to increase the minimum amount of frames.

I'll review the code later ;)

**Comment by Victorma** [comment]
@bridgewaterrobbie I've been talking today to the guy that lended me the Leap and he has told me that he noticed also the palm issue. Perhaps we should just wait a little and update the SDK then, when the error is fixed?

**Comment by bridgewaterrobbie** [comment]
@Victorma 
Possibly, though I can't tell for sure if this is an incompatibility/change in how they handle things, or a bug in Leap. I personally can't wait so I'm pivoting (Im using this as one piece for a school project, and can't let the leap's issues hold me back), though I would love to revisit the leap implementation if it is fixed after my project is done.

It might be worth emailing Leap and calling their attention to this, if it is a bug they might try tackling it.

**Pull request merged**
